"""add species categories, species, and species-destinations link

Revision ID: 020f6017db22
Revises: a2fdc2c18eb9
Create Date: 2026-08-30 11:33:19.203729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020f6017db22'
down_revision: Union[str, Sequence[str], None] = 'a2fdc2c18eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('count_label', sa.String(length=100), nullable=True),
    sa.Column('group', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_categories_slug'), 'species_categories', ['slug'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('common_name', sa.String(length=150), nullable=False),
    sa.Column('somali_name', sa.String(length=150), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('taxonomic_group', sa.String(length=150), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('editorial_statement', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('habitat', sa.String(length=255), nullable=True),
    sa.Column('depth', sa.String(length=100), nullable=True),
    sa.Column('distribution', sa.Text(), nullable=True),
    sa.Column('diet', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('lifespan', sa.String(length=100), nullable=True),
    sa.Column('conservation_status', sa.Enum('LEAST_CONCERN', 'NEAR_THREATENED', 'VULNERABLE', 'ENDANGERED', 'CRITICALLY_ENDANGERED', 'DATA_DEFICIENT', name='conservation_status'), nullable=False),
    sa.Column('status_explanation', sa.Text(), nullable=True),
    sa.Column('interesting_facts', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['species_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_slug'), 'species', ['slug'], unique=True)
    op.create_table('species_destinations',
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'destination_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_destinations')
    op.drop_index(op.f('ix_species_slug'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_species_categories_slug'), table_name='species_categories')
    op.drop_table('species_categories')
    # ### end Alembic commands ###
