"""add organization settings and contact submissions

Revision ID: 03d26bd5e4eb
Revises: 4d4fe60edea8
Create Date: 2026-08-30 12:36:13.535061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d26bd5e4eb'
down_revision: Union[str, Sequence[str], None] = '4d4fe60edea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mission_statement', sa.String(length=500), nullable=True),
    sa.Column('mission_description', sa.Text(), nullable=True),
    sa.Column('vision_statement', sa.String(length=500), nullable=True),
    sa.Column('vision_description', sa.Text(), nullable=True),
    sa.Column('story_intro', sa.Text(), nullable=True),
    sa.Column('story_paragraphs', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('why_ocean_matters_heading', sa.String(length=255), nullable=True),
    sa.Column('why_ocean_matters_text', sa.Text(), nullable=True),
    sa.Column('who_we_work_with_heading', sa.String(length=255), nullable=True),
    sa.Column('who_we_work_with_text', sa.Text(), nullable=True),
    sa.Column('what_we_do', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact_subjects', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_settings')
    op.drop_table('contact_submissions')
    # ### end Alembic commands ###
