"""media uploaded_by set null on user delete

Revision ID: 05ea90722e2f
Revises: d9de382f243e
Create Date: 2026-08-30 12:47:44.626635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ea90722e2f'
down_revision: Union[str, Sequence[str], None] = 'd9de382f243e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_uploaded_by_id_fkey'), 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key(op.f('media_uploaded_by_id_fkey'), 'media', 'users', ['uploaded_by_id'], ['id'])
    # ### end Alembic commands ###
