"""add video_url to media-bearing resources, research_observations to species

Revision ID: 0f80afd414e5
Revises: 80275ef301d7
Create Date: 2026-09-02 11:30:04.449435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f80afd414e5'
down_revision: Union[str, Sequence[str], None] = '80275ef301d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_stories', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('conservation_projects', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('destinations', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('experiences', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('news_articles', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('research_projects', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('species', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('species', sa.Column('research_observations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'research_observations')
    op.drop_column('species', 'video_url')
    op.drop_column('research_projects', 'video_url')
    op.drop_column('news_articles', 'video_url')
    op.drop_column('experiences', 'video_url')
    op.drop_column('destinations', 'video_url')
    op.drop_column('conservation_projects', 'video_url')
    op.drop_column('community_stories', 'video_url')
    # ### end Alembic commands ###
