"""add conservation and communities content

Revision ID: 32c52c41984f
Revises: 6778055772a4
Create Date: 2026-08-30 12:18:01.209222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c52c41984f'
down_revision: Union[str, Sequence[str], None] = '6778055772a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('livelihoods', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('marine_connection', sa.Text(), nullable=True),
    sa.Column('conservation_activities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_slug'), 'communities', ['slug'], unique=True)
    op.create_table('conservation_focus_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conservation_focus_areas_slug'), 'conservation_focus_areas', ['slug'], unique=True)
    op.create_table('conservation_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conservation_issues_slug'), 'conservation_issues', ['slug'], unique=True)
    op.create_table('conservation_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('focus_area_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'COMING_SOON', name='conservation_project_status'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('editorial_statement', sa.Text(), nullable=True),
    sa.Column('what_it_is', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('who_is_involved', sa.Text(), nullable=True),
    sa.Column('aims', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['focus_area_id'], ['conservation_focus_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conservation_projects_slug'), 'conservation_projects', ['slug'], unique=True)
    op.create_table('community_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('conservation_project_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('story_content', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('marine_connection', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['conservation_project_id'], ['conservation_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_stories_slug'), 'community_stories', ['slug'], unique=True)
    op.create_table('conservation_project_communities',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'community_id')
    )
    op.create_table('conservation_project_destinations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'destination_id')
    )
    op.create_table('conservation_project_issues',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['conservation_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'issue_id')
    )
    op.create_table('conservation_project_research_projects',
    sa.Column('conservation_project_id', sa.UUID(), nullable=False),
    sa.Column('research_project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conservation_project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conservation_project_id', 'research_project_id')
    )
    op.create_table('conservation_project_species',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'species_id')
    )
    op.create_table('community_story_species',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['community_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'species_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_story_species')
    op.drop_table('conservation_project_species')
    op.drop_table('conservation_project_research_projects')
    op.drop_table('conservation_project_issues')
    op.drop_table('conservation_project_destinations')
    op.drop_table('conservation_project_communities')
    op.drop_index(op.f('ix_community_stories_slug'), table_name='community_stories')
    op.drop_table('community_stories')
    op.drop_index(op.f('ix_conservation_projects_slug'), table_name='conservation_projects')
    op.drop_table('conservation_projects')
    op.drop_index(op.f('ix_conservation_issues_slug'), table_name='conservation_issues')
    op.drop_table('conservation_issues')
    op.drop_index(op.f('ix_conservation_focus_areas_slug'), table_name='conservation_focus_areas')
    op.drop_table('conservation_focus_areas')
    op.drop_index(op.f('ix_communities_slug'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
