"""add video title, description, source fields

Revision ID: 40ae4d726452
Revises: b01d43e78bb4
Create Date: 2026-09-02 13:43:29.238431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ae4d726452'
down_revision: Union[str, Sequence[str], None] = 'b01d43e78bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_stories', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('community_stories', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('community_stories', sa.Column('video_source', sa.String(length=255), nullable=True))
    op.add_column('conservation_projects', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('conservation_projects', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('conservation_projects', sa.Column('video_source', sa.String(length=255), nullable=True))
    op.add_column('destinations', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('destinations', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('destinations', sa.Column('video_source', sa.String(length=255), nullable=True))
    op.add_column('experiences', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('experiences', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('experiences', sa.Column('video_source', sa.String(length=255), nullable=True))
    op.add_column('news_articles', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('news_articles', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('news_articles', sa.Column('video_source', sa.String(length=255), nullable=True))
    op.add_column('research_projects', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('research_projects', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('research_projects', sa.Column('video_source', sa.String(length=255), nullable=True))
    op.add_column('species', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('species', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('species', sa.Column('video_source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'video_source')
    op.drop_column('species', 'video_description')
    op.drop_column('species', 'video_title')
    op.drop_column('research_projects', 'video_source')
    op.drop_column('research_projects', 'video_description')
    op.drop_column('research_projects', 'video_title')
    op.drop_column('news_articles', 'video_source')
    op.drop_column('news_articles', 'video_description')
    op.drop_column('news_articles', 'video_title')
    op.drop_column('experiences', 'video_source')
    op.drop_column('experiences', 'video_description')
    op.drop_column('experiences', 'video_title')
    op.drop_column('destinations', 'video_source')
    op.drop_column('destinations', 'video_description')
    op.drop_column('destinations', 'video_title')
    op.drop_column('conservation_projects', 'video_source')
    op.drop_column('conservation_projects', 'video_description')
    op.drop_column('conservation_projects', 'video_title')
    op.drop_column('community_stories', 'video_source')
    op.drop_column('community_stories', 'video_description')
    op.drop_column('community_stories', 'video_title')
    # ### end Alembic commands ###
