"""add news content

Revision ID: 4d4fe60edea8
Revises: 32c52c41984f
Create Date: 2026-08-30 12:28:31.864657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d4fe60edea8'
down_revision: Union[str, Sequence[str], None] = '32c52c41984f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('badge_class', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_categories_slug'), 'news_categories', ['slug'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('display_date', sa.String(length=50), nullable=True),
    sa.Column('read_time', sa.String(length=50), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_slug'), 'news_articles', ['slug'], unique=True)
    op.create_table('news_article_communities',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'community_id')
    )
    op.create_table('news_article_conservation_projects',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('conservation_project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conservation_project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'conservation_project_id')
    )
    op.create_table('news_article_destinations',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'destination_id')
    )
    op.create_table('news_article_experiences',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'experience_id')
    )
    op.create_table('news_article_research_projects',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('research_project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'research_project_id')
    )
    op.create_table('news_article_species',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'species_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_article_species')
    op.drop_table('news_article_research_projects')
    op.drop_table('news_article_experiences')
    op.drop_table('news_article_destinations')
    op.drop_table('news_article_conservation_projects')
    op.drop_table('news_article_communities')
    op.drop_index(op.f('ix_news_articles_slug'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_news_categories_slug'), table_name='news_categories')
    op.drop_table('news_categories')
    # ### end Alembic commands ###
