"""user profile fields, activity log, team members

Revision ID: 60e76384803b
Revises: 26d1a1e68bdb
Create Date: 2026-08-30 22:55:09.881717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60e76384803b'
down_revision: Union[str, Sequence[str], None] = '26d1a1e68bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('expertise', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_slug'), 'team_members', ['slug'], unique=True)
    op.create_table('activity_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'PUBLISHED', name='activity_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_entries_created_at'), 'activity_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_log_entries_user_id'), 'activity_log_entries', ['user_id'], unique=False)
    op.create_table('team_member_conservation_projects',
    sa.Column('team_member_id', sa.UUID(), nullable=False),
    sa.Column('conservation_project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conservation_project_id'], ['conservation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_member_id', 'conservation_project_id')
    )
    op.create_table('team_member_research_projects',
    sa.Column('team_member_id', sa.UUID(), nullable=False),
    sa.Column('research_project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['research_project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_member_id', 'research_project_id')
    )
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # NOT NULL with a server_default so existing rows backfill instead of
    # failing the migration — matches the model's Python-side default.
    op.add_column(
        'users',
        sa.Column(
            'notification_preferences',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(
                '\'{"new_contact_messages": true, "volunteer_enquiries": true, '
                '"partnership_enquiries": true, "new_article_published": false, '
                '"system_updates": false}\'::jsonb'
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_table('team_member_research_projects')
    op.drop_table('team_member_conservation_projects')
    op.drop_index(op.f('ix_activity_log_entries_user_id'), table_name='activity_log_entries')
    op.drop_index(op.f('ix_activity_log_entries_created_at'), table_name='activity_log_entries')
    op.drop_table('activity_log_entries')
    op.drop_index(op.f('ix_team_members_slug'), table_name='team_members')
    op.drop_table('team_members')
    # ### end Alembic commands ###
