"""add applications, notifications, contact submission user_id, user interests

Revision ID: 80275ef301d7
Revises: 8913c1ae5bd0
Create Date: 2026-09-01 06:31:30.924515

users.interests is added with a temporary server_default so existing
rows backfill to '[]' (Postgres requires a default to satisfy NOT NULL
against a non-empty table); the default is dropped right after so new
rows rely on the model's Python-side default instead, same pattern as
the existing contact_submissions.is_favorite migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80275ef301d7'
down_revision: Union[str, Sequence[str], None] = '8913c1ae5bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('application_type', sa.Enum('VOLUNTEER', 'PARTNER', 'SUPPORT', name='application_type'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'REVIEWING', 'ACCEPTED', 'DECLINED', name='application_status'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('contact_submissions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contact_submissions_user_id'), 'contact_submissions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'contact_submissions', 'users', ['user_id'], ['id'])
    op.add_column(
        'users',
        sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")),
    )
    op.alter_column('users', 'interests', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_constraint(None, 'contact_submissions', type_='foreignkey')
    op.drop_index(op.f('ix_contact_submissions_user_id'), table_name='contact_submissions')
    op.drop_column('contact_submissions', 'user_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
