"""add is_favorite to contact_submissions

Revision ID: 81e3ec5edbcc
Revises: 60e76384803b
Create Date: 2026-08-31 10:52:56.272598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e3ec5edbcc'
down_revision: Union[str, Sequence[str], None] = '60e76384803b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_submissions', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('contact_submissions', 'is_favorite', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_submissions', 'is_favorite')
    # ### end Alembic commands ###
