"""add saved items and experience interests

Revision ID: 8913c1ae5bd0
Revises: d210844d5200
Create Date: 2026-09-01 05:54:42.705172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8913c1ae5bd0'
down_revision: Union[str, Sequence[str], None] = 'd210844d5200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('INTERESTED', 'UPCOMING', 'COMPLETED', name='experience_interest_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_slug', name='uq_experience_interest_user_experience')
    )
    op.create_index(op.f('ix_experience_interests_user_id'), 'experience_interests', ['user_id'], unique=False)
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('DESTINATION', 'SPECIES', 'EXPERIENCE', 'RESEARCH', name='saved_item_type'), nullable=False),
    sa.Column('content_slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_slug', name='uq_saved_item_user_content')
    )
    op.create_index(op.f('ix_saved_items_user_id'), 'saved_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_items_user_id'), table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index(op.f('ix_experience_interests_user_id'), table_name='experience_interests')
    op.drop_table('experience_interests')
    # ### end Alembic commands ###
