"""add bilingual EN/SO support: destination translations, user and org language prefs

Revision ID: 8d9e77bf2303
Revises: 40ae4d726452
Create Date: 2026-09-04 02:17:03.560011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d9e77bf2303'
down_revision: Union[str, Sequence[str], None] = '40ae4d726452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('highlights', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'language', name='uq_destination_translation_language')
    )
    op.create_index(op.f('ix_destination_translations_destination_id'), 'destination_translations', ['destination_id'], unique=False)
    op.add_column(
        'organization_settings',
        sa.Column('enabled_languages', sa.ARRAY(sa.String()), server_default='{en,so}', nullable=False),
    )
    op.add_column('organization_settings', sa.Column('default_language', sa.String(length=5), server_default='en', nullable=False))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('organization_settings', 'default_language')
    op.drop_column('organization_settings', 'enabled_languages')
    op.drop_index(op.f('ix_destination_translations_destination_id'), table_name='destination_translations')
    op.drop_table('destination_translations')
    # ### end Alembic commands ###
