"""add regions and destinations tables

Revision ID: a2fdc2c18eb9
Revises: dc9cbc98c126
Create Date: 2026-08-30 11:20:38.749673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2fdc2c18eb9'
down_revision: Union[str, Sequence[str], None] = 'dc9cbc98c126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('coastline_km', sa.String(length=100), nullable=True),
    sa.Column('seas', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('highlights', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_slug'), 'regions', ['slug'], unique=True)
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('coastline_area', sa.String(length=255), nullable=True),
    sa.Column('destination_type', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('best_season', sa.String(length=255), nullable=True),
    sa.Column('access', sa.String(length=255), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('highlights', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_regions_slug'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
