"""add research areas, methodologies, teams, projects, and expeditions

Revision ID: ae14a5b51030
Revises: 020f6017db22
Create Date: 2026-08-30 11:50:36.062956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae14a5b51030'
down_revision: Union[str, Sequence[str], None] = '020f6017db22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methodologies_slug'), 'methodologies', ['slug'], unique=True)
    op.create_table('research_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('border_color', sa.String(length=50), nullable=True),
    sa.Column('text_color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_areas_slug'), 'research_areas', ['slug'], unique=True)
    op.create_table('research_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_teams_slug'), 'research_teams', ['slug'], unique=True)
    op.create_table('expeditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('dates', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('research_team_id', sa.UUID(), nullable=True),
    sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['research_areas.id'], ),
    sa.ForeignKeyConstraint(['research_team_id'], ['research_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expeditions_slug'), 'expeditions', ['slug'], unique=True)
    op.create_table('research_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('research_team_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'PUBLISHED', name='project_status'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('editorial_statement', sa.Text(), nullable=True),
    sa.Column('research_question', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('geographic_scope', sa.Text(), nullable=True),
    sa.Column('expected_outcomes', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objectives', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conservation_themes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['research_areas.id'], ),
    sa.ForeignKeyConstraint(['research_team_id'], ['research_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_slug'), 'research_projects', ['slug'], unique=True)
    op.create_table('team_focus_areas',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['research_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['research_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'area_id')
    )
    op.create_table('expedition_species',
    sa.Column('expedition_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expedition_id', 'species_id')
    )
    op.create_table('project_destinations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'destination_id')
    )
    op.create_table('project_methodologies',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('methodology_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'methodology_id')
    )
    op.create_table('project_species',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'species_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_species')
    op.drop_table('project_methodologies')
    op.drop_table('project_destinations')
    op.drop_table('expedition_species')
    op.drop_table('team_focus_areas')
    op.drop_index(op.f('ix_research_projects_slug'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_expeditions_slug'), table_name='expeditions')
    op.drop_table('expeditions')
    op.drop_index(op.f('ix_research_teams_slug'), table_name='research_teams')
    op.drop_table('research_teams')
    op.drop_index(op.f('ix_research_areas_slug'), table_name='research_areas')
    op.drop_table('research_areas')
    op.drop_index(op.f('ix_methodologies_slug'), table_name='methodologies')
    op.drop_table('methodologies')
    # ### end Alembic commands ###
