"""add google places photo caching to destinations

Revision ID: b01d43e78bb4
Revises: 0f80afd414e5
Create Date: 2026-09-02 11:54:28.434320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b01d43e78bb4'
down_revision: Union[str, Sequence[str], None] = '0f80afd414e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.add_column(
        'destinations',
        sa.Column('google_photos_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    op.add_column('destinations', sa.Column('google_photos_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'google_photos_fetched_at')
    op.drop_column('destinations', 'google_photos_cache')
    op.drop_column('destinations', 'google_place_id')
    # ### end Alembic commands ###
